apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: central-worker
  namespace: cve-track
  labels:
    app: central-worker
  annotations:
    image.toolkit.fluxcd.io/image: docker.truebyteinnovation.com/cve-track/main/cvetrack-central
    fluxcd.io/automated: "true"
    fluxcd.io/branch: "master"
    fluxcd.io/commit: "auto"
    fluxcd.io/url: "https://github.com/abhijoc85"
    application.kubernetes.io/name: "central-worker"
    application.kubernetes.io/instance: "master"
    application.kubernetes.io/version: "1.0.0"
    application.kubernetes.io/component: "worker"
    application.kubernetes.io/part-of: "cvetrack"
    application.kubernetes.io/managed-by: "flux"
    application.kubernetes.io/created-by: "Cursor AI"
spec:
  chart:
    spec:
      chart: service-deployment
      sourceRef:
        kind: HelmRepository
        name: nexus
        namespace: flux-system
      version: 1.2.0
  interval: 24h
  releaseName: central-worker
  targetNamespace: cve-track
  suspend: false
  timeout: 5m
  values:
    replicaCount: 1
   image: docker.truebyteinnovation.com/cve-track/main/cvetrack-central:1191 # {"$imagepolicy": "flux-system:cvetrack-central-policy"}
    imagePullPolicy: Always
    imagePullSecrets:
      - name: docker-registry-secret
    command:
      - "celery"
    args:
      - "-A"
      - "central.celery"
      - "worker"
      - "-l"
      - "INFO"
      - "-Q"
      - "schema_creation,default"
    livenessProbe: {}
    readinessProbe: {}
    resources:
      enable: true
      limits:
        cpu: 600m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 1Gi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    ingress:
      enabled: false
    externalConfigMaps:
      - name: cvetrack-common-config
    externalSecrets:
      - name: cvetrack-db-secret
      - name: cvetrack-app-secret
      - name: cvetrack-redis-secret
      - name: cvetrack-email-secret
      - name: cvetrack-jwt-secret
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: env
    #               operator: In
    #               values:
    #                 - dev
    #             - key: app
    #               operator: In
    #               values:
    #                 - cvetrack
    topologySpreadConstraints:
      enabled: true
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
