apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cvetrack-ui-helm-release
  namespace: cve-track
  labels:
    app: cvetrack-ui
  annotations:
    image.toolkit.fluxcd.io/image: docker.truebyteinnovation.com/cve-track/main/ui-dashboard
    fluxcd.io/automated: "true"
    fluxcd.io/branch: "main"
    fluxcd.io/commit: "auto"
    fluxcd.io/url: "https://github.com/abhijoc85"
    application.kubernetes.io/name: "cvetrack-ui"
    application.kubernetes.io/instance: "main"
    application.kubernetes.io/version: "1.0.0"
    application.kubernetes.io/component: "ui"
    application.kubernetes.io/part-of: "cvetrack"
    application.kubernetes.io/managed-by: "flux"
    application.kubernetes.io/created-by: "Cursor AI"
spec:
  chart:
    spec:
      chart: service-deployment
      sourceRef:
        kind: HelmRepository
        name: nexus
        namespace: flux-system
      version: 1.2.0
  interval: 24h
  releaseName: cvetrack-ui
  targetNamespace: cve-track
  suspend: false
  timeout: 5m
  values:
    replicaCount: 1
    image: docker.truebyteinnovation.com/cve-track/main/ui-dashboard:1194 # {"$imagepolicy": "flux-system:cvetrack-ui-policy"}
    imagePullPolicy: Always
    imagePullSecrets:
      - name: docker-registry-secret
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    service:
      type: ClusterIP
      port: 80
    resources:
      enable: true
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/secure-backends: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/enable-access-log: "false"
      hosts:
        - host: app.cvetrack.ai
          paths:
            - path: /
              pathType: ImplementationSpecific
    externalConfigMaps:
      - name: cvetrack-common-config
    externalSecrets:
      - name: cvetrack-app-secret
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: env
    #               operator: In
    #               values:
    #                 - dev
    #             - key: app
    #               operator: In
    #               values:
    #                 - cvetrack
    topologySpreadConstraints:
      enabled: false
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
